#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: server
#spec:
#  rules:
#  - http:
#      paths:
#        - pathType: Prefix
#          path: "/"
#          backend:
#            service:
#              name: todo-list-service
#              port:
#                number: 8080
