apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
#allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  #  mountOptions:
  #    - hard
  #    - nfsvers=4.0
  hostPath:
    path: "/data/psql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgres
  labels:
    app: postgres
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi